<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableSdkContainerSupport>true</EnableSdkContainerSupport>
    <ContainerRepository>blazorscheduler-demo</ContainerRepository>
    <ContainerPort>8080</ContainerPort>
    <ContainerUser>1654</ContainerUser>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.11" />
    <ProjectReference Include="..\BlazorScheduler.Demo.Client\BlazorScheduler.Demo.Client.csproj" />
  </ItemGroup>
</Project>
